// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Severity = ("INFO" | "WARNING" | "ERROR")

export interface Users {
  boolean: boolean;
  editorFileContent: EditorFileContent;
  roleMeta: RoleMeta[];
  userContext: UserContext;
  userEditorData: UserEditorData;
  userSaveDataArgs: UserSaveDataArgs;
  validationResult: ValidationResult[];
  [k: string]: unknown;
}
export interface EditorFileContent {
  content: string;
}
export interface RoleMeta {
  id: string;
  label: string;
}
export interface UserContext {
  app: string;
  file: string;
  pmv: string;
}
export interface UserEditorData {
  context: UserContext;
  data: UserData[];
  helpUrl: string;
  readonly: boolean;
}
export interface UserData {
  emailAddress: string;
  fullName: string;
  name: string;
  password: string;
  properties: MapStringString;
  roles: string[];
}
export interface MapStringString {
  [k: string]: string;
}
export interface UserSaveDataArgs {
  context: UserContext;
  data: UserData[];
  directSave: boolean;
}
export interface ValidationResult {
  message: string;
  path: string;
  severity: Severity;
}
